
# This file contains the contracts between the agent and tools.

# Import Decimal so that financial calculations are accurate.
from decimal import Decimal

# Import Literal so that some fields can only contain predefined values.
from typing import Literal

# Import BaseModel and Field from Pydantic v2.
from pydantic import BaseModel, Field


# -----------------------------
# Clause Risk Models
# -----------------------------

# Input model for the clause-risk calculator.
class RiskRequest(BaseModel):

    # Type of clause being evaluated.
    clause_type: str

    # Total commercial value of the contract.
    contract_value: Decimal = Field(gt=0)

    # Position proposed by the counterparty.
    contract_position: Decimal

    # Position defined by the internal playbook.
    playbook_position: Decimal


# Output model returned by the risk calculator.
class RiskResult(BaseModel):

    # Clause that was evaluated.
    clause_type: str

    # Calculated risk score from 0 to 100.
    risk_score: float = Field(ge=0, le=100)

    # Business-friendly risk classification.
    risk_level: Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"]

    # Percentage difference from the playbook.
    deviation: float

    # Human-readable explanation.
    explanation: str


# -----------------------------
# Renewal Calendar Models
# -----------------------------

# Input model for renewal-date calculation.
class RenewalRequest(BaseModel):

    # Unique contract identifier.
    contract_id: str

    # Contract renewal date in YYYY-MM-DD format.
    renewal_date: str

    # Number of days before renewal when notice is required.
    notice_period: int = Field(ge=0)


# Output model from the renewal calculator.
class RenewalEvent(BaseModel):

    # Unique contract identifier.
    contract_id: str

    # Original renewal date.
    renewal_date: str

    # Date by which notice must be given.
    notice_deadline: str

    # Urgency classification.
    urgency: Literal["NORMAL", "URGENT", "CRITICAL"]


# -----------------------------
# Contract Summary
# -----------------------------

# Small contract summary used by the memo writer.
class ContractSummary(BaseModel):

    # Contract identifier.
    contract_id: str

    # Name of the counterparty.
    counterparty: str

    # Contract value.
    contract_value: Decimal

    # Short description of the contract.
    description: str


# -----------------------------
# Memo Models
# -----------------------------

# Input model for memo creation.
class MemoRequest(BaseModel):

    # Contract information.
    contract: ContractSummary

    # Risk results generated by the risk tool.
    risks: list[RiskResult]

    # Renewal information generated by the calendar tool.
    renewal: RenewalEvent


# Output model from the memo writer.
class MemoResult(BaseModel):

    # Location of the generated memo.
    file_path: str

    # Actual memo content.
    content: str


# -----------------------------
# Agent Request / Response
# -----------------------------

# Input received by the FastAPI endpoint.
class ReviewRequest(BaseModel):

    # Contract information.
    contract: ContractSummary

    # Risk calculations to perform.
    risk_requests: list[RiskRequest]

    # Renewal information.
    renewal: RenewalRequest


# Final response returned by the agent.
class ReviewResponse(BaseModel):

    # Generated risk results.
    risks: list[RiskResult]

    # Generated renewal event.
    renewal: RenewalEvent

    # Generated memo information.
    memo: MemoResult

    # Tools actually used by the agent.
    tools_used: list[str]

    # Explicit record of actions that were not allowed.
    unauthorized_actions: list[str]